# Server
server.port=8080

spring.main.allow-circular-references=true
# PostgreSQL - Render Database
spring.datasource.url=jdbc:postgresql://dpg-d7brlnqa214c73elad70-a:5432/sentiment_dashboard_db
spring.datasource.username=sentiment_dashboard_db_user
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Disable Kafka in production
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.listener.auto-startup=false
spring.kafka.consumer.auto-startup=false

# API Keys
api.huggingface.key=${HUGGINGFACE_KEY}
api.gnews.key=${GNEWS_KEY}
api.finnhub.key=${FINNHUB_KEY}
api.coingecko.key=${COINGECKO_KEY}
